
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: one_on_one_development

test:
  <<: *default
  database: one_on_one_test

production:
  url: <%= ENV['DATABASE_URL'] %>
